# Generated by Django 2.2.5 on 2019-10-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', models.CharField(max_length=200)),
                ('card_heading', models.CharField(max_length=30)),
                ('card_subtitle', models.CharField(max_length=40)),
                ('card_paragraph', models.CharField(max_length=400)),
            ],
        ),
    ]
