# Generated by Django 2.2.5 on 2019-10-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_paragraph',
            field=models.TextField(),
        ),
    ]
