# Generated by Django 2.2.5 on 2019-10-19 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_post',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
